apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  labels:
    app: oom-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: oom-demo

  template:
    metadata:
      labels:
        app: oom-demo

    spec:
      containers:
        - name: oom-demo
          image: python:3.12-alpine

          command:
            - python
            - -c
            - |
              data = []
              while True:
                  data.append(bytearray(10 * 1024 * 1024))

          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "32Mi"